// src/merchants.js
export const defaultMerchants = [
  { id: "liverpool_central_grill", name: "Liverpool Central Grill", center: [53.407, -2.985], radiusMiles: 2.5, codes: [] },
  { id: "birken_burger_birkenhead", name: "Birken Burger (Birkenhead)", center: [53.392, -3.015], radiusMiles: 2.5, codes: [] },
  { id: "wallasey_wings", name: "Wallasey Wings", center: [53.425, -3.056], radiusMiles: 2.0, codes: [] },
  { id: "seacombe_shawarma", name: "Seacombe Shawarma", center: [53.418, -3.016], radiusMiles: 2.0, codes: [] },
  { id: "new_brighton_noodles", name: "New Brighton Noodles", center: [53.438, -3.039], radiusMiles: 2.0, codes: [] },
  { id: "west_kirby_kitchen", name: "West Kirby Kitchen", center: [53.373, -3.184], radiusMiles: 2.5, codes: [] },
  { id: "hoylake_hotbox", name: "Hoylake Hotbox", center: [53.391, -3.176], radiusMiles: 2.0, codes: [] },
  { id: "moreton_meals", name: "Moreton Meals", center: [53.405, -3.109], radiusMiles: 2.0, codes: [] },
  { id: "upton_urban_bites", name: "Upton Urban Bites", center: [53.389, -3.098], radiusMiles: 2.0, codes: [] },
  { id: "greasby_grill", name: "Greasby Grill", center: [53.378, -3.117], radiusMiles: 2.0, codes: [] },
  { id: "prenton_pizza", name: "Prenton Pizza", center: [53.371, -3.039], radiusMiles: 2.0, codes: [] },
  { id: "oxton_street_food", name: "Oxton Street Food", center: [53.376, -3.050], radiusMiles: 2.0, codes: [] },
  { id: "rock_ferry_rolls", name: "Rock Ferry Rolls", center: [53.364, -3.004], radiusMiles: 2.0, codes: [] },
  { id: "new_ferry_fast_food", name: "New Ferry Fast Food", center: [53.357, -2.996], radiusMiles: 2.0, codes: [] },
  { id: "bebington_bites", name: "Bebington Bites", center: [53.351, -3.008], radiusMiles: 2.0, codes: [] },
  { id: "bromborough_box", name: "Bromborough Box", center: [53.333, -2.989], radiusMiles: 2.0, codes: [] },
  { id: "eastham_eats", name: "Eastham Eats", center: [53.315, -2.973], radiusMiles: 2.0, codes: [] },
  { id: "heswall_hub", name: "Heswall Hub", center: [53.327, -3.096], radiusMiles: 2.0, codes: [] },
  { id: "pensby_patties", name: "Pensby Patties", center: [53.343, -3.102], radiusMiles: 2.0, codes: [] },
  { id: "liscard_larder", name: "Liscard Larder", center: [53.421, -3.048], radiusMiles: 2.0, codes: [] },

  { id: "bootle_burgers", name: "Bootle Burgers", center: [53.456, -2.989], radiusMiles: 2.0, codes: [] },
  { id: "crosby_chicken", name: "Crosby Chicken", center: [53.486, -3.028], radiusMiles: 2.0, codes: [] },
  { id: "kirkby_kebabs", name: "Kirkby Kebabs", center: [53.483, -2.889], radiusMiles: 2.0, codes: [] },
  { id: "huyton_hotpot", name: "Huyton Hotpot", center: [53.411, -2.841], radiusMiles: 2.0, codes: [] },
  { id: "speke_spice", name: "Speke Spice", center: [53.344, -2.855], radiusMiles: 2.0, codes: [] },
  { id: "garston_griddle", name: "Garston Griddle", center: [53.359, -2.915], radiusMiles: 2.0, codes: [] },
  { id: "woolton_wraps", name: "Woolton Wraps", center: [53.375, -2.871], radiusMiles: 2.0, codes: [] },
  { id: "wavertree_wok", name: "Wavertree Wok", center: [53.402, -2.927], radiusMiles: 2.0, codes: [] },
  { id: "anfield_bites", name: "Anfield Bites", center: [53.430, -2.961], radiusMiles: 2.0, codes: [] },
  { id: "everton_eats", name: "Everton Eats", center: [53.419, -2.966], radiusMiles: 2.0, codes: [] },
  { id: "toxteth_tacos", name: "Toxteth Tacos", center: [53.385, -2.956], radiusMiles: 2.0, codes: [] },
  { id: "walton_wings", name: "Walton Wings", center: [53.459, -2.961], radiusMiles: 2.0, codes: [] }
];
